name: 'Check for artifacts'
description: 'Test whether a set of artifacts exist'
inputs:
  filter-file:
    description: Path to the file defining the job filters
    required: true
  workflow-file:
    description: Path to the workflow file
    required: true
  storage-account:
    description: Storage account name
    required: true
  container:
    description: Container name
    required: true
outputs:
  jobs:
    description: JSON object keyed on job name with values including whether the job's artifact exists and its artifact key
runs:
  using: 'node20'
  main: 'dist/index.js'
